### ISSUE TITLE
Request for upstreaming the changes

### ISSUE THREAD

**Issue by aminya** [GrayJack/language-python-treesitter#1]
I would love to see a PR to the upstream repo.

I am using some of your changes here in this PR:
https://github.com/atom/language-python/pull/325/files

**Comment by aminya** [comment]
OK, I upstreamed most of the changes here:
https://github.com/atom/language-python/pull/325/files

Thanks!

**Comment by GrayJack** [comment]
Glad it was upstreamed, I don't use Atom anymore, so I'm not taking so much care as I would like to maintain Atom packages.

Soon I'll push a commit to tell at the readme to continue to use the upstream version and archive this one once it is accepted  😁
